info:
    foo: bar

server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: pgssoft
    keyStoreType: PKCS12
    keyAlias: tomcat

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/schooldaily
    username: pgsuser
    password: pgspass

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show_sql: true

logging:
  level:
    org:
      springframework: DEBUG
